package it.unibs.pajc;

public class CostantiStatiche {

    public static final int TABLE_WIDTH = 1200;
    public static final int TABLE_HEIGHT = 600;
    public static final int BORDER_WIDTH = 50;
    public static final int POCKET_RADIUS = 30;
    public static final int BIG_POCKET_RADIUS = 35;

    public static final int[][] X_POINTS_TRAPEZI =  {
            //TRAPEZIO 1
            {BORDER_WIDTH + BIG_POCKET_RADIUS, TABLE_WIDTH / 2 - POCKET_RADIUS,
                    TABLE_WIDTH / 2 - POCKET_RADIUS - BORDER_WIDTH / 2, BORDER_WIDTH + POCKET_RADIUS * 2},
            //TRAPEZIO 2
            {TABLE_WIDTH / 2 + POCKET_RADIUS, TABLE_WIDTH - BIG_POCKET_RADIUS - BORDER_WIDTH,
                    TABLE_WIDTH - BORDER_WIDTH - POCKET_RADIUS * 2, TABLE_WIDTH / 2 + POCKET_RADIUS + BORDER_WIDTH / 2},
            //TRAPEZIO 3
            {BORDER_WIDTH, BORDER_WIDTH + BORDER_WIDTH / 2, BORDER_WIDTH + BORDER_WIDTH / 2, BORDER_WIDTH},
            //TRAPEZIO 4
            {BORDER_WIDTH + POCKET_RADIUS + BORDER_WIDTH / 2, TABLE_WIDTH / 2 - POCKET_RADIUS - BORDER_WIDTH / 2,
                    TABLE_WIDTH / 2 - POCKET_RADIUS, BORDER_WIDTH + BIG_POCKET_RADIUS},
            //TRAPEZIO 5
            {TABLE_WIDTH / 2 + POCKET_RADIUS * 2, TABLE_WIDTH - BIG_POCKET_RADIUS * 2 - BORDER_WIDTH,
                    TABLE_WIDTH - BIG_POCKET_RADIUS - BORDER_WIDTH, TABLE_WIDTH / 2 + POCKET_RADIUS},
            //TRAPEZIO 6
            {TABLE_WIDTH - BORDER_WIDTH - BORDER_WIDTH / 2, TABLE_WIDTH - BORDER_WIDTH, TABLE_WIDTH - BORDER_WIDTH,
                    TABLE_WIDTH - BORDER_WIDTH - BORDER_WIDTH / 2}
    };

    public static final int[][] Y_POINTS_TRAPEZI = {
            //TRAPEZIO 1
            {BORDER_WIDTH, BORDER_WIDTH, BORDER_WIDTH + BORDER_WIDTH / 2, BORDER_WIDTH + BORDER_WIDTH / 2},
            //TRAPEZIO 2
            {BORDER_WIDTH, BORDER_WIDTH, BORDER_WIDTH + BORDER_WIDTH / 2, BORDER_WIDTH + BORDER_WIDTH / 2},
            //TRAPEZIO 3
            {BORDER_WIDTH + BIG_POCKET_RADIUS, BORDER_WIDTH + BIG_POCKET_RADIUS + BORDER_WIDTH / 2,
                    TABLE_HEIGHT - BORDER_WIDTH - BIG_POCKET_RADIUS - BORDER_WIDTH / 2,
                    TABLE_HEIGHT - BORDER_WIDTH - BIG_POCKET_RADIUS},
            //TRAPEZIO 4
            {TABLE_HEIGHT - BORDER_WIDTH - BORDER_WIDTH / 2, TABLE_HEIGHT - BORDER_WIDTH - BORDER_WIDTH / 2,
                    TABLE_HEIGHT - BORDER_WIDTH, TABLE_HEIGHT - BORDER_WIDTH},
            //TRAPEZIO 5
            {TABLE_HEIGHT - BORDER_WIDTH - BORDER_WIDTH / 2, TABLE_HEIGHT - BORDER_WIDTH - BORDER_WIDTH / 2,
                    TABLE_HEIGHT - BORDER_WIDTH, TABLE_HEIGHT - BORDER_WIDTH},
            //TRAPEZIO 6
            {BORDER_WIDTH + BIG_POCKET_RADIUS + BORDER_WIDTH / 2, BORDER_WIDTH + BIG_POCKET_RADIUS,
                    TABLE_HEIGHT - BORDER_WIDTH - BIG_POCKET_RADIUS,
                    TABLE_HEIGHT - BORDER_WIDTH - BIG_POCKET_RADIUS - BORDER_WIDTH / 2}
    };
}
